# -*- coding: utf-8 -*-
{
    'name': "返修",
    'summary': "返修",
    'description': "返修",
    'author': "My Company",
    'version': '0.1',
    'depends': ['base', 'mail', 'hpro', 'warehouse_management', 'fsn_outsource'],
    'data':[
        'views/general.xml',
        'views/invest_invest.xml',
        'views/general_general.xml',
        'views/client_warehouse_repair.xml',
        'views/day_style_repair_statistics.xml',
        'views/middle_check_efficiency.xml',
        'views/always_check_efficiency.xml',
        'views/middle_check_omission_factor.xml',
        'views/middle_check_workpiece_ratio.xml',
        'views/middle_check_day_leak.xml',
        'views/group_statistical.xml',
        'views/employees_statistical.xml',
        'views/posterior_passage_statistical.xml',
        'views/always_check_efficiency_day.xml',
        'views/client_ware.xml',
        'views/station_twice_send_back.xml',
        'views/always_check_omission.xml',
        'views/always_check_omission_details.xml',
        'views/middle_check_missed_details.xml',
        'views/always_check_omission_month.xml',
        'views/quality_control_collect.xml',
        'views/repair_stranded.xml',
        'views/quality_records.xml',
        'views/sealed_samples_first.xml',
        'views/inspection_warehouse.xml',
        'views/first_eight_pieces.xml',
        'views/middle_check_month_efficiency.xml',
        'views/general_inspection_month_efficiency.xml',
        'views/client_ware_repair_statistics.xml',
        'views/menu.xml',
        ],
    'sequence':1,
    'application': True,
}

