# -*- coding: utf-8 -*-
{
    'name': "薪酬管理",
    'summary': "薪酬管理",
    'description': "薪酬管理",
    'author': "XU",
    'version': '0.1',
    'depends': ['base', 'fsn_base', 'hr', 'mail', 'fsn_employee'],
    'data': [
        'security/salary_management_security.xml',
        'views/views.xml',
        'views/dormitory_property_fee.xml',
        'views/set_up_attendance_days.xml',
        'views/templates.xml',
        'views/set_up_basic.xml',
        'views/calendar.xml',
        'views/refill_card_return.xml',
        'views/TransientModel.xml',
        'views/deduct_money_setting.xml',
        'views/salary_sheet.xml',
        'views/true_salary_sheet.xml',
        'views/outsourcing_wages_per_work_time.xml',
        'views/outsourcing_wages_for_work_done.xml',
        'views/outsourcing_wages_wizard.xml',
        'views/compensation_statistics.xml',
        'views/workshop_pie_chart.xml',
        'views/amoeba_chart.xml',
        'views/compensation_sublevel.xml',
        'views/payroll1.xml',
        'views/payroll2.xml',
        'views/payroll3.xml',
        'views/efficiency_wages_setting.xml',
        'data/group_leader_wages_setting_data.xml',
        'views/post_performance_setting.xml',
        'views/post_commission_setting.xml',
        'views/salary_lock_setting.xml',
        'views/efficiency_bonus_setting.xml',
        'views/menu.xml',
    ],
    'qweb': [
        'static/src/xml/workshop_pie_chart.xml',
        'static/src/xml/amoeba_chart.xml',
    ],
    'sequence': 1,
    'application': True,
}